name: Run PLM_BOT

on:
  schedule:
    - cron: '00 00 * * 1-6' 

jobs:
  run_python:
    name: Run Python Script
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Python script
      run: python main.py 
      env:
        DEVELOPER_KEY: ${{ secrets.DEVELOPER_KEY }}
        TLG_TOKEN: ${{ secrets.TLG_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
          commit_message: Update video_id
